
COPY public.actividades (id, tema, actividad_id, subdireccion_id, servicio_id, persona_responsable, tiempo_aproximado, fecha_programada, modalidad_id, estado_id, detalles, metadatos, mes_id) FROM stdin;
44	Trabajo en Equipo y Habilidades Blandas	2	6	3	{"r0": {"nombre": "Juan Mario Cordon", "puesto": "Educador"}}	1 hora	2025-10-08	3	1	{"mes": 0, "nota": "prueba de sistema", "bueno": 0, "regular": 0, "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0}	{"user": "sistema", "registro": "2025-10-26T17:03:27.677Z"}	10
35	Salud Mental	2	4	1	{"r0": {"nombre": "Lcda. CIndy Martínez", "puesto": "Psicológa"}}	30 minutos	2025-08-31	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal Asistencial", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
23	Redaccion de documentos para traslado de información 	1	4	2	{"r0": {"nombre": "", "puesto": "Subdirectora Técnica"}}	1 hora	2025-07-30	1	1	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Jefes de servicio de la subdirección Técnica ", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	7
19	Inteligencia Emocional en el Liderazgo	2	6	3	{"r0": {"nombre": "Gladis Argueta", "puesto": "Encargada del Subgrupo 18"}}	1 hora	2025-07-30	1	1	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "A todos los jefes de departamentos y servicios. (PENDIENTE DE REPROGRAMACIÓN)", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	7
17	Choque séptico en Pediatría	2	3	4	{"r0": {"nombre": "Dr. Fredy Chalí", "puesto": "Jefe"}}	1 hora	2025-07-30	2	1	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Médicos Pediatras", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	7
24	Trauma Craneoencefálico	2	3	5	{"r0": {"nombre": "", "puesto": "Cirujano"}}	1 hora	2025-07-30	2	1	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "DEPARTAMENTO DE CIRUGÍA", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	7
22	Ética Médica	2	1	6	{"r0": {"nombre": "", "puesto": "Subdirectora médica"}}	1 hora	2025-07-30	2	1	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "JEFES DE DEPARTAMENTO", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	7
30	Hipertensión intraoperatoria: bases fisiológicas y manejo	2	3	7	{"r0": {"nombre": "Dra. Ana Lucía Pérez", "puesto": "Jefa del Departamento"}, "r1": {"nombre": "Dr. Marlon López", "puesto": "Invitado"}}	1 hora	2025-08-20	2	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
2	Beneficios de la Lactancia Materna	1	4	8	{"r0": {"nombre": "Licda. Angelica Chiquito", "puesto": "Nutricionista"}}	2 horas	2025-05-30	1	3	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	5
8	Interpretación Resultados de Química	1	4	9	{"r0": {"nombre": "Lic. Marvynn Coy", "puesto": "Jefe"}}	1 hora	2025-06-27	1	1	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	6
37	Manejo de Desechos Sólidos Hospitalarios según Acuerdo Gubernativo 509-2001	2	4	10	{"r0": {"nombre": "Ing. Ambiental", "puesto": "Gestor Ambiental"}}	1.5 horas	2025-08-31	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Todo el Personal (Personal operativo, asistencial, administrativo y médico)", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
21	Manejo de Desechos Sólidos Hospitalarios según Acuerdo Gubernativo 509-2001	2	4	10	{"r0": {"nombre": "Ing.", "puesto": "Gestor Ambiental"}}	1.5 horas	2025-07-25	1	3	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1.5 horas", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Estudiantes Practicantes", "fecha_entrega_informe": "2025-08-01"}	{"user": "", "registro": ""}	7
10	Manejo de Desechos Sólidos Hospitalarios según Acuerdo Gubernativo 509-2001	2	4	10	{"r0": {"nombre": "Ing. Ambiental", "puesto": "Gestor Ambiental"}}	1.5 horas	2025-06-30	1	3	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Estudiantes Médicos Externos", "fecha_entrega_informe": "2025-06-13"}	{"user": "", "registro": ""}	6
42	Gastronomía Hospitalaria	2	4	11	{"r0": {"nombre": "Lcda. Angélica Chiquitó", "puesto": "Encargada del Departamento"}}	30 minutos	2025-08-31	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Dirigido a personal del Servicio de Alimentación", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
12	Manipulación de alimentos	2	4	11	{"r0": {"nombre": "Lcda. Angélica Chiquitó", "puesto": "Encargada"}}	1 hora	2025-06-30	1	1	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	6
11	Herramientas de comunicación para la educación en salud de adultos	2	4	11	{"r0": {"nombre": "Lcda. Angélica Chiquitó", "puesto": "Encargada"}}	1 hora	2025-06-30	1	1	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	6
14	Bress de medicamentos	1	5	12	{"r0": {"nombre": "Eddy Hernández", "puesto": "Bodeguero"}}	1 hora	2025-07-30	1	1	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	7
5	Manejo de Desechos Solidos Hospitalarios Según Acuerdo Gubernativo 509	2	1	13	{"r0": {"nombre": "", "puesto": ""}}	1 hora 30 minutos	2025-05-30	1	1	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	5
31	Medidas de Seguridad	2	4	14	{"r0": {"nombre": "Dra. Lesbia Coló", "puesto": "Jefa del Departamento"}}	1 hora	2025-08-23	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
26	Salud mental	2	5	15	{"r0": {"nombre": "Lcda. Flor Eguizabal", "puesto": "Psicologa"}}	1 hora	2025-08-29	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "SERVICIOS GENERALES Y MANTENIMIENTO", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
15	Retroalimentación de manejo adecuado de desechos Sólidos Hospitalarios y Comunes	1	5	15	{"r0": {"nombre": "Mery Cúc", "puesto": "Encargada"}}	2 horas	2025-07-30	1	3	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": "2025-07-30"}	{"user": "", "registro": ""}	7
41	1. Técnicas de alimentación en recién nacidos 2. Limpieza terminal y concurrente 3. Cuidado humanizado 4. Oxigenoterapia y aerosolterapia 	1	2	16	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-29	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
40	1. Limpieza concurrente y terminal 2. Cuidado humanizado 3. Monitoreo materno fetal 4. Atención y cuidados de pacientes con quemaduras	1	2	16	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-28	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
38	1. Atención y cuidados de pacientes con quemaduras 2. Atención de paciente politraumatizado 3. Cuidados post-mortem	1	2	16	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-26	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
39	1. Oxigenoterapia y aerosolterapia 2. Manejo de medicamentos para inducción y conducción del trabajo de parto  3. Manejo de monitores materno fetal  4. Manejo de instrumental quirúrgico 	1	2	16	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-27	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
7	Traslado sin afectación en libros y traslados con afectación en libros en el  Módulo de Inventarios de SICOIN	1	5	17	{"r0": {"nombre": "Christian Gomez", "puesto": "Encargado"}}	1 hora	2025-06-09	1	3	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": "2025-07-15"}	{"user": "", "registro": ""}	6
4	Obligaciones y derechos de los trabajadores	2	1	18	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Asesor Juridico"}}	1 hora	2025-05-30	1	1	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	5
32	Uso de Tecnologías de computo	2	4	19	{"r0": {"nombre": "Ronald Chacón", "puesto": "Encargado del departamento"}}	1 horas	2025-08-28	2	2	{"mes": 8, "link": "https://meet.google.com/yhw-rati-fsu", "nota": "14:00 A 15:00 HORAS", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "TIPS DE EXECEL Y USO DE IA EN ENTORNO ADMINISTRATIVO", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal Administrativo", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
13	Plan educacional (Prevención en Salud bucal)	2	4	20	{"r0": {"nombre": "Dra. Erika Meléndez", "puesto": "Odontóloga"}}	45 minutos	2025-06-30	1	1	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	6
34	Actualización del Manejo de Síndrome del Ovario Poliquístico	2	3	21	{"r0": {"nombre": "Dra. Karen Junay", "puesto": "Jefa del Departamento"}}	50 minutos	2025-08-22	2	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
3	Manejo Medicamentoso para el Aborto Incompleto: Misoprostol y Mifepristona	2	3	21	{"r0": {"nombre": "Dra. Karen Junay", "puesto": "Ginecóloga"}}	50 minutos	2025-05-15	2	1	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	5
36	La evaluación de desempeño y sus efectos	2	1	22	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Asesor Jurídico"}}	1 hora	2025-08-31	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
20	Conflictos de las normas juridicas laborales CAMBIO POR Consideraciones Generales de la Ley de Acceso a la Información Pública	2	1	22	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Jurídico"}}	1 hora	2025-07-30	1	3	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal de recursos humanos", "fecha_entrega_informe": "2025-08-01"}	{"user": "", "registro": ""}	7
9	Obligaciones de los Contratistas	2	1	22	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Asesor Jurídico"}}	1 hora	2025-06-30	1	3	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": "2025-07-14"}	{"user": "", "registro": ""}	6
27	NPG y Inclusión de Códigos a SIGES	2	5	23	{"r0": {"nombre": "Astrid Argelia Oliva", "puesto": "Analista de compras"}}	1 hora	2025-08-31	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
16	Compras Directas, Npg y Contrato Abierto	2	5	23	{"r0": {"nombre": "Ronald Orrego", "puesto": "Encargado"}}	1 hora	2025-07-30	1	1	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	7
18	Clasificación de desechos 	1	1	24	{"r0": {"nombre": "Gerente Administrativo Financiero", "puesto": "Gerencia"}}	1 hora	2025-07-22	1	1	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	7
25	Atención al paciente 	2	4	25	{"r0": {"nombre": "Luis Fernando Miza Chalí", "puesto": "Radiólogo"}}	45 minutos	2025-07-11	1	3	{"mes": 7, "link": "", "nota": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 7, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal de Rayos X", "fecha_entrega_informe": "2025-08-05"}	{"user": "", "registro": ""}	7
29	Síndrome Metabólico y Riesgo Cardiovascular	2	3	26	{"r0": {"nombre": "Dra. Cuín y Médico EPS", "puesto": "Jefa de Departamento"}}	50 minutos	2025-08-20	2	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
28	Síndrome Metabólico y Riesgo Cardiovascular	2	3	26	{"r0": {"nombre": "Dra. Cuín y Médico EPS", "puesto": "Jefa de Departamento"}}	50 minutos	2025-08-20	2	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
6	 Buenas practicas de almacenamiento 	2	4	27	{"r0": {"nombre": "Elsa Hernandez Ramón", "puesto": "Encargada"}}	1/2 hora	2025-06-03	1	1	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	6
33	Normativas vigentes	1	4	29	{"r0": {"nombre": "Lcda. Heidi Santos", "puesto": "Jefa del Departamento"}}	1 hora	2025-08-13	1	1	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}	8
43	Infección de sitio quirúrgico sop	2	3	28	{"r0": {"nombre": "Dr. Luis Ávalos", "puesto": "Jefe del Departamento"}}	2 horas	2025-08-31	1	2	{"mes": 8, "nota": "otra prueba", "bueno": 0, "regular": 0, "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0}	{"user": "sistema", "registro": "2025-10-25T18:52:33.406Z"}	8
\.

--
-- Data for Name: actividades_backup; Type: TABLE DATA; Schema: public; Owner: mide
--


COPY public.actividades_backup (id, tema, actividad, servicio_encargado, persona_responsable, tiempo_aproximado, fechas_a_desarrollar, modalidad, estado, detalles, metadatos) FROM stdin;
3	Manejo Medicamentoso para el Aborto Incompleto: Misoprostol y Mifepristona	2	GINECOLOGÍA Y OBSTETRICIA	{"r0": {"nombre": "Dra. Karen Junay", "puesto": "Ginecóloga"}}	50 minutos	2025-05-15	V	P	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
4	Obligaciones y derechos de los trabajadores	2	Asesoría Juridica	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Asesor Juridico"}}	1 hora	2025-05-30	P	P	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
5	Manejo de Desechos Solidos Hospitalarios Según Acuerdo Gubernativo 509	2	Comite de Desechos Solidos Hospitalarios	{"r0": {"nombre": "", "puesto": ""}}	1 hora 30 minutos	2025-05-30	P	P	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
2	Beneficios de la Lactancia Materna	1	Nutrición	{"r0": {"nombre": "Licda. Angelica Chiquito", "puesto": "Nutricionista"}}	2 horas	2025-05-30	P	C	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
6	 Buenas practicas de almacenamiento 	2	PRODUCTOS AFINES	{"r0": {"nombre": "Elsa Hernandez Ramón", "puesto": "Encargada"}}	1/2 hora	2025-06-03	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
15	Retroalimentación de manejo adecuado de desechos Sólidos Hospitalarios y Comunes	1	SERVICIOS GENERALES Y MANTENIMIENTO	{"r0": {"nombre": "Mery Cúc", "puesto": "Encargada"}}	2 horas	2025-07-30	P	C	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": "2025-07-30"}	{"user": "", "registro": ""}
8	Interpretación Resultados de Química	1	LABORATORIO CLÍNICO	{"r0": {"nombre": "Lic. Marvynn Coy", "puesto": "Jefe"}}	1 hora	2025-06-27	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
11	Herramientas de comunicación para la educación en salud de adultos	2	NUTRICIÓN	{"r0": {"nombre": "Lcda. Angélica Chiquitó", "puesto": "Encargada"}}	1 hora	2025-06-30	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
12	Manipulación de alimentos	2	NUTRICIÓN	{"r0": {"nombre": "Lcda. Angélica Chiquitó", "puesto": "Encargada"}}	1 hora	2025-06-30	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
13	Plan educacional (Prevención en Salud bucal)	2	ODONTOLOGÍA	{"r0": {"nombre": "Dra. Erika Meléndez", "puesto": "Odontóloga"}}	45 minutos	2025-06-30	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
14	Bress de medicamentos	1	BODEGA	{"r0": {"nombre": "Eddy Hernández", "puesto": "Bodeguero"}}	1 hora	2025-07-30	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
16	Compras Directas, Npg y Contrato Abierto	2	COMPRAS	{"r0": {"nombre": "Ronald Orrego", "puesto": "Encargado"}}	1 hora	2025-07-30	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
7	Traslado sin afectación en libros y traslados con afectación en libros en el  Módulo de Inventarios de SICOIN	1	INVENTARIO DE ACTIVOS FIJOS	{"r0": {"nombre": "Christian Gomez", "puesto": "Encargado"}}	1 hora	2025-06-09	P	C	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": "2025-07-15"}	{"user": "", "registro": ""}
10	Manejo de Desechos Sólidos Hospitalarios según Acuerdo Gubernativo 509-2001	2	GESTIÓN AMBIENTAL	{"r0": {"nombre": "Ing. Ambiental", "puesto": "Gestor Ambiental"}}	1.5 horas	2025-06-30	P	C	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Estudiantes Médicos Externos", "fecha_entrega_informe": "2025-06-13"}	{"user": "", "registro": ""}
17	Choque séptico en Pediatría	2	PEDIATRÍA	{"r0": {"nombre": "Dr. Fredy Chalí", "puesto": "Jefe"}}	1 hora	2025-07-30	V	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Médicos Pediatras", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
23	Redaccion de documentos para traslado de información 	1	SUBDIRECCIÓN TÉCNICA	{"r0": {"nombre": "", "puesto": "Subdirectora Técnica"}}	1 hora	2025-07-30	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Jefes de servicio de la subdirección Técnica ", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
9	Obligaciones de los Contratistas	2	ASESORÍA JURÍDICA	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Asesor Jurídico"}}	1 hora	2025-06-30	P	C	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": "2025-07-14"}	{"user": "", "registro": ""}
19	Inteligencia Emocional en el Liderazgo	2	RECURSOS HUMANOS	{"r0": {"nombre": "Gladis Argueta", "puesto": "Encargada del Subgrupo 18"}}	1 hora	2025-07-30	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "A todos los jefes de departamentos y servicios. (PENDIENTE DE REPROGRAMACIÓN)", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
21	Manejo de Desechos Sólidos Hospitalarios según Acuerdo Gubernativo 509-2001	2	GESTIÓN AMBIENTAL	{"r0": {"nombre": "Ing.", "puesto": "Gestor Ambiental"}}	1.5 horas	2025-07-25	P	C	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1.5 horas", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Estudiantes Practicantes", "fecha_entrega_informe": "2025-08-01"}	{"user": "", "registro": ""}
25	Atención al paciente 	2	RAYOS X	{"r0": {"nombre": "Luis Fernando Miza Chalí", "puesto": "Radiólogo"}}	45 minutos	2025-07-11	P	C	{"mes": 7, "link": "", "nota": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 7, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal de Rayos X", "fecha_entrega_informe": "2025-08-05"}	{"user": "", "registro": ""}
18	Clasificación de desechos 	1	GERENCIA ADMINISTRATIVA FINANCIERA	{"r0": {"nombre": "Gerente Administrativo Financiero", "puesto": "Gerencia"}}	1 hora	2025-07-22	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
22	Ética Médica	2	SUBDIRECCIÓN MÉDICA	{"r0": {"nombre": "", "puesto": "Subdirectora médica"}}	1 hora	2025-07-30	V	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "JEFES DE DEPARTAMENTO", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
24	Trauma Craneoencefálico	2	CIRUGÍA	{"r0": {"nombre": "", "puesto": "Cirujano"}}	1 hora	2025-07-30	V	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "DEPARTAMENTO DE CIRUGÍA", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
34	Actualización del Manejo de Síndrome del Ovario Poliquístico	2	GINECOLOGÍA Y OBSTETRICIA	{"r0": {"nombre": "Dra. Karen Junay", "puesto": "Jefa del Departamento"}}	50 minutos	2025-08-22	V	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
20	Conflictos de las normas juridicas laborales CAMBIO POR Consideraciones Generales de la Ley de Acceso a la Información Pública	2	ASESORÍA JURÍDICA	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Jurídico"}}	1 hora	2025-07-30	P	C	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal de recursos humanos", "fecha_entrega_informe": "2025-08-01"}	{"user": "", "registro": ""}
26	Salud mental	2	SERVICIOS GENERALES Y MANTENIMIENTO	{"r0": {"nombre": "Lcda. Flor Eguizabal", "puesto": "Psicologa"}}	1 hora	2025-08-29	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "SERVICIOS GENERALES Y MANTENIMIENTO", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
27	NPG y Inclusión de Códigos a SIGES	2	COMPRAS	{"r0": {"nombre": "Astrid Argelia Oliva", "puesto": "Analista de compras"}}	1 hora	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
28	Síndrome Metabólico y Riesgo Cardiovascular	2	MEDICINA INTERNA	{"r0": {"nombre": "Dra. Cuín y Médico EPS", "puesto": "Jefa de Departamento"}}	50 minutos	2025-08-20	V	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
29	Síndrome Metabólico y Riesgo Cardiovascular	2	MEDICINA INTERNA	{"r0": {"nombre": "Dra. Cuín y Médico EPS", "puesto": "Jefa de Departamento"}}	50 minutos	2025-08-20	V	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
30	Hipertensión intraoperatoria: bases fisiológicas y manejo	2	ANESTESIOLOGÍA	{"r0": {"nombre": "Dra. Ana Lucía Pérez", "puesto": "Jefa del Departamento"}, "r1": {"nombre": "Dr. Marlon López", "puesto": "Invitado"}}	1 hora	2025-08-20	V	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
31	Medidas de Seguridad	2	EPIDEMIOLOGÍA	{"r0": {"nombre": "Dra. Lesbia Coló", "puesto": "Jefa del Departamento"}}	1 hora	2025-08-23	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
33	Normativas vigentes	1	FARMACIA	{"r0": {"nombre": "Lcda. Heidi Santos", "puesto": "Jefa del Departamento"}}	1 hora	2025-08-13	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
35	Salud Mental	2	PSICOLOGÍA	{"r0": {"nombre": "Lcda. CIndy Martínez", "puesto": "Psicológa"}}	30 minutos	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal Asistencial", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
36	La evaluación de desempeño y sus efectos	2	ASESORÍA JURÍDICA	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Asesor Jurídico"}}	1 hora	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
39	1. Oxigenoterapia y aerosolterapia 2. Manejo de medicamentos para inducción y conducción del trabajo de parto  3. Manejo de monitores materno fetal  4. Manejo de instrumental quirúrgico 	1	SUBDIRECCIÓN DE ENFERMERÍA	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-27	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
42	Gastronomía Hospitalaria	2	NUTRICIÓN	{"r0": {"nombre": "Lcda. Angélica Chiquitó", "puesto": "Encargada del Departamento"}}	30 minutos	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Dirigido a personal del Servicio de Alimentación", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
37	Manejo de Desechos Sólidos Hospitalarios según Acuerdo Gubernativo 509-2001	2	GESTIÓN AMBIENTAL	{"r0": {"nombre": "Ing. Ambiental", "puesto": "Gestor Ambiental"}}	1.5 horas	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Todo el Personal (Personal operativo, asistencial, administrativo y médico)", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
38	1. Atención y cuidados de pacientes con quemaduras 2. Atención de paciente politraumatizado 3. Cuidados post-mortem	1	SUBDIRECCIÓN DE ENFERMERÍA	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-26	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
40	1. Limpieza concurrente y terminal 2. Cuidado humanizado 3. Monitoreo materno fetal 4. Atención y cuidados de pacientes con quemaduras	1	SUBDIRECCIÓN DE ENFERMERÍA	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-28	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
41	1. Técnicas de alimentación en recién nacidos 2. Limpieza terminal y concurrente 3. Cuidado humanizado 4. Oxigenoterapia y aerosolterapia 	1	SUBDIRECCIÓN DE ENFERMERÍA	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-29	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
32	Uso de Tecnologías de computo	2	INFORMÁTICA	{"r0": {"nombre": "Ronald Chacón", "puesto": "Encargado del departamento"}}	1 horas	2025-08-28	V	R	{"mes": 8, "link": "https://meet.google.com/yhw-rati-fsu", "nota": "14:00 A 15:00 HORAS", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "TIPS DE EXECEL Y USO DE IA EN ENTORNO ADMINISTRATIVO", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal Administrativo", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
43	Infección de sitio quirúrgico	2	TRAUMATOLOGÍA Y ORTOPEDIA	{"r0": {"nombre": "Dr. Luis Ávalos", "puesto": "Jefe del Departamento"}}	2 horas	2025-08-31	P	R	{"mes": 8, "link": "", "nota": "otra prueba", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
\.

--
-- Data for Name: actividades_old; Type: TABLE DATA; Schema: public; Owner: mide
--


COPY public.actividades_old (id, tema, actividad, servicio_encargado, persona_responsable, tiempo_aproximado, fechas_a_desarrollar, modalidad, estado, detalles, metadatos) FROM stdin;
3	Manejo Medicamentoso para el Aborto Incompleto: Misoprostol y Mifepristona	2	GINECOLOGÍA Y OBSTETRICIA	{"r0": {"nombre": "Dra. Karen Junay", "puesto": "Ginecóloga"}}	50 minutos	2025-05-15	V	P	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
4	Obligaciones y derechos de los trabajadores	2	Asesoría Juridica	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Asesor Juridico"}}	1 hora	2025-05-30	P	P	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
5	Manejo de Desechos Solidos Hospitalarios Según Acuerdo Gubernativo 509	2	Comite de Desechos Solidos Hospitalarios	{"r0": {"nombre": "", "puesto": ""}}	1 hora 30 minutos	2025-05-30	P	P	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
2	Beneficios de la Lactancia Materna	1	Nutrición	{"r0": {"nombre": "Licda. Angelica Chiquito", "puesto": "Nutricionista"}}	2 horas	2025-05-30	P	C	{"mes": 5, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
6	 Buenas practicas de almacenamiento 	2	PRODUCTOS AFINES	{"r0": {"nombre": "Elsa Hernandez Ramón", "puesto": "Encargada"}}	1/2 hora	2025-06-03	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
15	Retroalimentación de manejo adecuado de desechos Sólidos Hospitalarios y Comunes	1	SERVICIOS GENERALES Y MANTENIMIENTO	{"r0": {"nombre": "Mery Cúc", "puesto": "Encargada"}}	2 horas	2025-07-30	P	C	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": "2025-07-30"}	{"user": "", "registro": ""}
8	Interpretación Resultados de Química	1	LABORATORIO CLÍNICO	{"r0": {"nombre": "Lic. Marvynn Coy", "puesto": "Jefe"}}	1 hora	2025-06-27	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
11	Herramientas de comunicación para la educación en salud de adultos	2	NUTRICIÓN	{"r0": {"nombre": "Lcda. Angélica Chiquitó", "puesto": "Encargada"}}	1 hora	2025-06-30	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
12	Manipulación de alimentos	2	NUTRICIÓN	{"r0": {"nombre": "Lcda. Angélica Chiquitó", "puesto": "Encargada"}}	1 hora	2025-06-30	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
13	Plan educacional (Prevención en Salud bucal)	2	ODONTOLOGÍA	{"r0": {"nombre": "Dra. Erika Meléndez", "puesto": "Odontóloga"}}	45 minutos	2025-06-30	P	P	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
14	Bress de medicamentos	1	BODEGA	{"r0": {"nombre": "Eddy Hernández", "puesto": "Bodeguero"}}	1 hora	2025-07-30	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
16	Compras Directas, Npg y Contrato Abierto	2	COMPRAS	{"r0": {"nombre": "Ronald Orrego", "puesto": "Encargado"}}	1 hora	2025-07-30	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
7	Traslado sin afectación en libros y traslados con afectación en libros en el  Módulo de Inventarios de SICOIN	1	INVENTARIO DE ACTIVOS FIJOS	{"r0": {"nombre": "Christian Gomez", "puesto": "Encargado"}}	1 hora	2025-06-09	P	C	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": "2025-07-15"}	{"user": "", "registro": ""}
10	Manejo de Desechos Sólidos Hospitalarios según Acuerdo Gubernativo 509-2001	2	GESTIÓN AMBIENTAL	{"r0": {"nombre": "Ing. Ambiental", "puesto": "Gestor Ambiental"}}	1.5 horas	2025-06-30	P	C	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Estudiantes Médicos Externos", "fecha_entrega_informe": "2025-06-13"}	{"user": "", "registro": ""}
17	Choque séptico en Pediatría	2	PEDIATRÍA	{"r0": {"nombre": "Dr. Fredy Chalí", "puesto": "Jefe"}}	1 hora	2025-07-30	V	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Médicos Pediatras", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
23	Redaccion de documentos para traslado de información 	1	SUBDIRECCIÓN TÉCNICA	{"r0": {"nombre": "", "puesto": "Subdirectora Técnica"}}	1 hora	2025-07-30	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Jefes de servicio de la subdirección Técnica ", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
9	Obligaciones de los Contratistas	2	ASESORÍA JURÍDICA	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Asesor Jurídico"}}	1 hora	2025-06-30	P	C	{"mes": 6, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": "2025-07-14"}	{"user": "", "registro": ""}
19	Inteligencia Emocional en el Liderazgo	2	RECURSOS HUMANOS	{"r0": {"nombre": "Gladis Argueta", "puesto": "Encargada del Subgrupo 18"}}	1 hora	2025-07-30	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "A todos los jefes de departamentos y servicios. (PENDIENTE DE REPROGRAMACIÓN)", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
21	Manejo de Desechos Sólidos Hospitalarios según Acuerdo Gubernativo 509-2001	2	GESTIÓN AMBIENTAL	{"r0": {"nombre": "Ing.", "puesto": "Gestor Ambiental"}}	1.5 horas	2025-07-25	P	C	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1.5 horas", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Estudiantes Practicantes", "fecha_entrega_informe": "2025-08-01"}	{"user": "", "registro": ""}
25	Atención al paciente 	2	RAYOS X	{"r0": {"nombre": "Luis Fernando Miza Chalí", "puesto": "Radiólogo"}}	45 minutos	2025-07-11	P	C	{"mes": 7, "link": "", "nota": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 7, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal de Rayos X", "fecha_entrega_informe": "2025-08-05"}	{"user": "", "registro": ""}
18	Clasificación de desechos 	1	GERENCIA ADMINISTRATIVA FINANCIERA	{"r0": {"nombre": "Gerente Administrativo Financiero", "puesto": "Gerencia"}}	1 hora	2025-07-22	P	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
22	Ética Médica	2	SUBDIRECCIÓN MÉDICA	{"r0": {"nombre": "", "puesto": "Subdirectora médica"}}	1 hora	2025-07-30	V	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "JEFES DE DEPARTAMENTO", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
24	Trauma Craneoencefálico	2	CIRUGÍA	{"r0": {"nombre": "", "puesto": "Cirujano"}}	1 hora	2025-07-30	V	P	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "1 hora", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "DEPARTAMENTO DE CIRUGÍA", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
34	Actualización del Manejo de Síndrome del Ovario Poliquístico	2	GINECOLOGÍA Y OBSTETRICIA	{"r0": {"nombre": "Dra. Karen Junay", "puesto": "Jefa del Departamento"}}	50 minutos	2025-08-22	V	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
20	Conflictos de las normas juridicas laborales CAMBIO POR Consideraciones Generales de la Ley de Acceso a la Información Pública	2	ASESORÍA JURÍDICA	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Jurídico"}}	1 hora	2025-07-30	P	C	{"mes": 7, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal de recursos humanos", "fecha_entrega_informe": "2025-08-01"}	{"user": "", "registro": ""}
26	Salud mental	2	SERVICIOS GENERALES Y MANTENIMIENTO	{"r0": {"nombre": "Lcda. Flor Eguizabal", "puesto": "Psicologa"}}	1 hora	2025-08-29	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "SERVICIOS GENERALES Y MANTENIMIENTO", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
27	NPG y Inclusión de Códigos a SIGES	2	COMPRAS	{"r0": {"nombre": "Astrid Argelia Oliva", "puesto": "Analista de compras"}}	1 hora	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
28	Síndrome Metabólico y Riesgo Cardiovascular	2	MEDICINA INTERNA	{"r0": {"nombre": "Dra. Cuín y Médico EPS", "puesto": "Jefa de Departamento"}}	50 minutos	2025-08-20	V	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
29	Síndrome Metabólico y Riesgo Cardiovascular	2	MEDICINA INTERNA	{"r0": {"nombre": "Dra. Cuín y Médico EPS", "puesto": "Jefa de Departamento"}}	50 minutos	2025-08-20	V	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
30	Hipertensión intraoperatoria: bases fisiológicas y manejo	2	ANESTESIOLOGÍA	{"r0": {"nombre": "Dra. Ana Lucía Pérez", "puesto": "Jefa del Departamento"}, "r1": {"nombre": "Dr. Marlon López", "puesto": "Invitado"}}	1 hora	2025-08-20	V	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
31	Medidas de Seguridad	2	EPIDEMIOLOGÍA	{"r0": {"nombre": "Dra. Lesbia Coló", "puesto": "Jefa del Departamento"}}	1 hora	2025-08-23	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
33	Normativas vigentes	1	FARMACIA	{"r0": {"nombre": "Lcda. Heidi Santos", "puesto": "Jefa del Departamento"}}	1 hora	2025-08-13	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
35	Salud Mental	2	PSICOLOGÍA	{"r0": {"nombre": "Lcda. CIndy Martínez", "puesto": "Psicológa"}}	30 minutos	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal Asistencial", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
36	La evaluación de desempeño y sus efectos	2	ASESORÍA JURÍDICA	{"r0": {"nombre": "Lic. Rudy Carpio", "puesto": "Asesor Jurídico"}}	1 hora	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
39	1. Oxigenoterapia y aerosolterapia 2. Manejo de medicamentos para inducción y conducción del trabajo de parto  3. Manejo de monitores materno fetal  4. Manejo de instrumental quirúrgico 	1	SUBDIRECCIÓN DE ENFERMERÍA	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-27	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
42	Gastronomía Hospitalaria	2	NUTRICIÓN	{"r0": {"nombre": "Lcda. Angélica Chiquitó", "puesto": "Encargada del Departamento"}}	30 minutos	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Dirigido a personal del Servicio de Alimentación", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
37	Manejo de Desechos Sólidos Hospitalarios según Acuerdo Gubernativo 509-2001	2	GESTIÓN AMBIENTAL	{"r0": {"nombre": "Ing. Ambiental", "puesto": "Gestor Ambiental"}}	1.5 horas	2025-08-31	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Todo el Personal (Personal operativo, asistencial, administrativo y médico)", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
38	1. Atención y cuidados de pacientes con quemaduras 2. Atención de paciente politraumatizado 3. Cuidados post-mortem	1	SUBDIRECCIÓN DE ENFERMERÍA	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-26	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
40	1. Limpieza concurrente y terminal 2. Cuidado humanizado 3. Monitoreo materno fetal 4. Atención y cuidados de pacientes con quemaduras	1	SUBDIRECCIÓN DE ENFERMERÍA	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-28	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
41	1. Técnicas de alimentación en recién nacidos 2. Limpieza terminal y concurrente 3. Cuidado humanizado 4. Oxigenoterapia y aerosolterapia 	1	SUBDIRECCIÓN DE ENFERMERÍA	{"r0": {"nombre": "Comité de Formación y  Capacitación", "puesto": ""}}	6 horas	2025-08-29	P	P	{"mes": 8, "link": "", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
32	Uso de Tecnologías de computo	2	INFORMÁTICA	{"r0": {"nombre": "Ronald Chacón", "puesto": "Encargado del departamento"}}	1 horas	2025-08-28	V	R	{"mes": 8, "link": "https://meet.google.com/yhw-rati-fsu", "nota": "14:00 A 15:00 HORAS", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "TIPS DE EXECEL Y USO DE IA EN ENTORNO ADMINISTRATIVO", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "Personal Administrativo", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
43	Infección de sitio quirúrgico	2	TRAUMATOLOGÍA Y ORTOPEDIA	{"r0": {"nombre": "Dr. Luis Ávalos", "puesto": "Jefe del Departamento"}}	2 horas	2025-08-31	P	R	{"mes": 8, "link": "", "nota": "otra prueba", "bueno": 0, "lugar": "", "regular": 0, "duracion": "", "contenido": "", "excelente": 0, "asistencia": 0, "deficiente": 0, "inasistencia": 0, "grupo_dirigido": "", "fecha_entrega_informe": ""}	{"user": "", "registro": ""}
\.